#Test
jobs:
  cx-scan:
    executor: cxflow/default
    steps:
      - checkout
      - cxflow/scan:
          preset: Checkmarx Express
          report-file: checkmarx.json
          sca-accessControlUrl: 'https://platform.checkmarx.net'
          sca-apiUrl: 'https://api.scacheckmarx.com'
          sca-appUrl: 'https://sca.scacheckmarx.com'
          scanners: 'sast'
          team: /CxServer/SP/ANZ/CBA-GH-POC
          version: '9.4'
          incremental: false
          params: '--cx-flow.thresholds.Medium=0'
      - store_artifacts:
          path: checkmarx.json
orbs:
  cxflow: checkmarx-ts/cxflow@1.0.5
version: 2.1
workflows:
  sast-scan:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
  version: 2